management:
    endpoint:
        health:
            probes:
                enabled: true
            show-details: never
    endpoints:
        web:
            exposure:
                include: health,info
server:
    port: ${PORT:8080}
spring:
    datasource:
#        url: ${SPRING_DATASOURCE_URL}
#        username: ${SPRING_DATASOURCE_USERNAME}
#        password: ${SPRING_DATASOURCE_PASSWORD}
        url: 'jdbc:postgresql://localhost:5432/travel-api'
        username: 'postgres'
        password: 'securepass'
    jackson:
        serialization:
            write-dates-as-timestamps: false
    jpa:
        hibernate:
            ddl-auto: validate
    flyway:
        enabled: true
        locations: classpath:db/migration



## Update env vars on the running deployment
#    kubectl set env deployment/fraud-check-service \
#    SPRING_DATASOURCE_URL='jdbc:postgresql://postgres:5432/amldb' \
#    SPRING_DATASOURCE_USERNAME=postgres \
#    SPRING_DATASOURCE_PASSWORD=securepass \
#    SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect \
#    SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
# --- security config start ---
security:
  jwt:
    issuer: "travel-planner-api"
    secret: ${JWT_SECRET:dev-insecure-change-me}
    ttlMinutes: 1440
  google:
    audiences: ${GOOGLE_AUDIENCES:your-ios-client-id.apps.googleusercontent.com,your-web-client-id.apps.googleusercontent.com}
  apple:
    audience: ${APPLE_AUDIENCE:com.your.bundle.id}
    issuer: https://appleid.apple.com
# --- security config end ---
