management:
    endpoint:
        health:
            probes:
                enabled: true
            show-details: never
    endpoints:
        web:
            exposure:
                include: health,info
server:
    port: ${PORT:8080}
spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jackson:
        serialization:
            write-dates-as-timestamps: false
    jpa:
        hibernate:
            ddl-auto: validate
    flyway:
        enabled: true
        locations: classpath:db/migration
# --- security config start ---
security:
  jwt:
    issuer: "travel-planner-api"
    secret: ${JWT_SECRET:dev-insecure-change-me}
    ttlMinutes: 1440
  google:
    audiences: ${GOOGLE_AUDIENCES:your-ios-client-id.apps.googleusercontent.com,your-web-client-id.apps.googleusercontent.com}
  apple:
    audience: ${APPLE_AUDIENCE:com.your.bundle.id}
    issuer: https://appleid.apple.com
# --- security config end ---
