management:
    endpoint:
        health:
            probes:
                enabled: true
            show-details: never
    endpoints:
        web:
            exposure:
                include: health,info
server:
    port: ${PORT:8080}
spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jackson:
        serialization:
            write-dates-as-timestamps: false
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        enabled: true
