management:
    endpoint:
        health:
            probes:
                enabled: true
            show-details: never
    endpoints:
        web:
            exposure:
                include: health,info
server:
    port: ${PORT:8080}
    tomcat:
        accesslog:
            enabled: true
            # remoteHost user authUser date request status bytes time userAgent
            pattern: '%h %l %u %t "%r" %s %b %Dms "%{User-Agent}i"'
spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}

    jackson:
        serialization:
            write-dates-as-timestamps: false
    jpa:
      hibernate:
        ddl-auto: none        # Flyway will manage schema
      open-in-view: false
      properties:
        hibernate.format_sql: true
    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:db/migration
logging:
  level:
    org.springframework.security: INFO
    # Keep app logs, but silence chatty JWT filter
    com.axora.travel: DEBUG
    com.axora.travel.security.JwtAuthFilter: ERROR
    root: INFO
    org.apache.coyote.http11: ERROR
    org.apache.tomcat.util.net: ERROR


## Update env vars on the running deployment
#    kubectl set env deployment/fraud-check-service \
#    SPRING_DATASOURCE_URL='jdbc:postgresql://postgres:5432/amldb' \
#    SPRING_DATASOURCE_USERNAME=postgres \
#    SPRING_DATASOURCE_PASSWORD=securepass \
#    SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect \
#    SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
# --- security config start ---
security:
  jwt:
    issuer: "travel-planner-api"
    secret: ${JWT_SECRET:dev-insecure-change-me}
    ttlMinutes: 1440
  google:
    clientId: 1009680597431-eiomjfr1s69l0u60hu0f2c91u1tsr90p.apps.googleusercontent.com
  apple:
    audience: com.example.travelPlannerApp
    issuer: https://appleid.apple.com
  # 👇 NEW: dev auth toggle (safe default false)
  # dev-auth toggle start
  devAuthEnabled: ${DEV_AUTH_ENABLED:false}
  # dev-auth toggle end
# --- security config end ---
