# Trigger Render Deploy (sanitized + encoded) start
- name: Trigger Render Deploy (sanitized + encoded)
  if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
  env:
    HOOK_RAW: ${{ secrets.RENDER_DEPLOY_HOOK }}
    IMAGE: docker.io/rahulkumartonk/travel-planner-api:latest
  run: |
    set -euo pipefail
    # Trim CR/LF and trailing spaces from the secret
    HOOK=$(printf %s "$HOOK_RAW" | tr -d '
  ' | sed 's/[[:space:]]*$//')
  echo "::add-mask::$HOOK"
  
  # If your Render service default image already matches Docker Hub, include imgURL
  # NOTE: imgURL must be URL-encoded and must match the service's default repo (only tag/digest may differ)
  ENCODED_IMG=$(python3 - <<'PY'
  import os, urllib.parse
  print(urllib.parse.quote(os.environ['IMAGE'], safe=''))
  PY
  )
  curl -fsSL "$HOOK?imgURL=$ENCODED_IMG"
# Trigger Render Deploy (sanitized + encoded) end