# Trigger Render Deploy (sanitized) start
- name: Trigger Render Deploy (sanitized)
  if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
  env:
    HOOK_RAW: ${{ secrets.RENDER_DEPLOY_HOOK }}
  run: |
    set -euo pipefail
    HOOK=$(printf %s "$HOOK_RAW" | tr -d '
  ' | sed 's/[[:space:]]*$//')
  echo "::add-mask::$HOOK"
  curl -fsSL "$HOOK"
# Trigger Render Deploy (sanitized) end